.editorconfig
.eslintrc.js
.prettierrc.js
README.md
app.js
config/config.js
migrations/20200921070147-create-role.js
migrations/20200921211634-create-user.js
models/index.js
models/role.js
models/user.js
package-lock.json
package.json
public/stylesheets/style.css
routes/index.js
routes/users.js
seeders/20201109013158-create-roles.js
seeders/20201109013159-create-demo-user.js

Configuration of linter, code formater and plugin. Also first execution of prettier --write . (npm run format:write)
to make the code format uniform.

[Add] Eslint, Prettier and editorconfig

---

.gitattributes
.gitconfig

Archivos para que prettier funcione bien en Windows con VS code

Windows Linter config

---

controllers/activitiesController.js
migrations/20220819151137-create-activities.js
models/activities.js
seeders/20220819151606-demo-activities.js

Modelo, migración, seeder y controlador base para activities.

Crear modelo, migracion y contrl activities

---

controllers/membersController.js
migrations/20220819032313-create-member.js
models/member.js
seeders/20220819043012-create-members.js

Se creo modelo, migrate, seeds

create model members

---

app.js
controllers/organizationController.js
routes/organization.js

Se agrego el endpoint organization/public , se creo en la carpeta routes el archivo organization.js y se agrego la peticion get al organizationController.

Ot264-24-organization-public-data

---

controllers/testimonialsController.js
migrations/20220818215452-create-testimonial.js
models/testimonial.js
seeders/20220822134358-demo-testimonial.js

Model, migrations and base controller of testimonials completed

testimonials model completed

---

controllers/activitiesController.js
migrations/20220819151137-create-activities.js
models/activities.js
seeders/20220819151606-demo-activities.js

Con la actualización mas reciente de Development, se agregaron los cuatro archivos relacionados con activities.

OT264-19-Create-Model-Categories

---

controllers/newsCategories.js
controllers/newsCategoriesController.js
migrations/20220819021502-create-categories.js
models/categories.js

Categories con mayusucula y se cambio el nombre de newsCategories -> newsCategoriesController

Ot264 -19- categories

---

controllers/roleController.js
models/role.js

Se crea asociación de clave foranea al model y se crea controller

Se agrega asociacion de kf y controller

---

models/role.js

hotfix role elimino asociacion de clave foranea en model

hotfix role

---

controllers/userController.js
routes/auth.js

Endpoint of login authentication

Login authentication

---

controllers/newsController.js
migrations/20220824040411-create-new.js
models/new.js
seeders/20220825020955-create-new.js

se crea model,controller,migrate,seeder de novedades

OT-20-create-new

---

controllers/userController.js
middlewares/roleValidator.js
utils/jwtUtils.js

Arreglo en la verificación de administrador. Tambien se mejora la verificación del token jwt desde el header Authorization - Bearer token

Fix token and admin role validations

---

middlewares/authentication.js
utils/error.js

COMO usuario autenticado
QUIERO restringir el acceso a cierto contenido
PARA mantener los datos protegidos

Ot 27 middleware authentication user

---

app.js
controllers/activitiesController.js
routes/activities.js

Endpoint for create activities

endpoint create activities

---

app.js
controllers/newsCategoriesController.js
routes/newsCategories.js

endpoint create categories

---

controllers/newsCategoriesController.js
routes/newsCategories.js

Ot46 endpoint eliminacion categorias

---

middlewares/authentication.js

Reusar codigo de utilidades para jwt y organización de flujo del código

Refractorizar middleware authentication

---

app.js
controllers/newsCategoriesController.js
controllers/newsController.js
migrations/20220824040411-create-new.js
models/new.js
models/organization.js
routes/news.js
routes/newsCategories.js
seeders/20220825020955-create-new.js

Se creo la petición getbyId para traer las novedades

OT-47 endpoint getbyid news

---

app.js
controllers/slidesController.js
routes/slides.js

OT-59_slide_detail

---

app.js
controllers/slidesController.js
routes/slides.js

OT-61_slides_update

---

middlewares/ownership.js

Creation of ownership middleware

OT-35_middleware_ownership

---

controllers/organizationController.js

Slides list in public organization controller + fix of spelling mistakes in controller

OT-63_slides_list

---

controllers/newsCategoriesController.js
routes/newsCategories.js

Mostra todos los campos de una categoría en base al id enviado por parámetro. En el caso de que no exista error 404

Ot 43 detalle categoria

---

app.js
controllers/contactsController.js
routes/contacts.js

Creación de contacto teniendo como punto de partida rama OT-56, debe aprovarse primero [PR 52](https://github.com/alkemyTech/OT264-server/pull/52) que contiene los seeder y migraciones de contactos para poder realizar la creación

Ot 57 create contact

---

controllers/slidesController.js
routes/slides.js

Listado de slides teniendo como punto de partida rama OT-61, debe aprovarse primero [PR 56](https://github.com/alkemyTech/OT264-server/pull/56) que contiene los archivos que involucran a slides

Ot 58 listado slides

---

app.js
controllers/membersController.js
routes/members.js

Endpoint for eliminate members

OT-76_eliminate_member

---

app.js
controllers/testimonialsController.js
routes/testimonial.js

Endpoint for update testimonials

OT-71_testimonial_update

---

controllers/slidesController.js
routes/slides.js

Eliminación de slides teniendo como punto de partida rama OT-58 -> [PR 58](https://github.com/alkemyTech/OT264-server/pull/58)

Ot 62 eliminar slide

---

controllers/newsController.js
routes/news.js

Se agrego el metodo updateNews en NewsController

Ot 49 endpoint actualización novedades

---

controllers/newsCategoriesController.js
controllers/userController.js
routes/newsCategories.js
utils/error.js

Muestra el listado de categories solo con campo name de las mismas

Ot 42 endpoint listado categoria

---

migrations/20220818231403-create-organization.js
seeders/20220819010605-demo-organization.js

Se agregaron campos de contactos a organizations

OT-67-agregar-campos-organizations

---

middlewares/ownership.js

ownership fixes

---

controllers/membersController.js
models/member.js
routes/members.js

Se agrego a membersController el metodo getall.

enpoint gettall members

---

controllers/newsController.js
routes/news.js

Valida la existencia en base al id enviado por parámetro. En el caso de que exista, se elimina

Ot 51 endpoint delete new

---

controllers/organizationController.js
routes/organization.js

COMO usuario
QUIERO ver los links de las redes sociales al entrar a la página

ver link de redes sociales

---

README.md
seeders/20220907212911-create-userAdmin-noAdmin.js

Se crearon 10 usuarios administradores y 10 usuarios no administtradores.

Ot 78 seed de usuarios

---

migrations/20220908045228-create-comment.js
models/comment.js
seeders/20220908051253-create-comments.js

Creacion de model, migration y seeder de entidad Comment.

Ot 80 migracion modelo comentarios

---

app.js
controllers/commentsController.js
routes/comments.js

list of comments

---

utils/uploadImageS3.js

Util for uploading images to S3 bucket

upload images via s3

---

docs/components/categories.schema.js
docs/components/index.js
docs/paths/category/category.path.js
docs/paths/category/index.js
docs/paths/index.js
docs/tags.js

Documentation of categories endpoints

categories documentation

---

routes/contacts.js
routes/members.js
routes/users.js

Se agrego middleware de rol administrador para proteger rutas.

Ot 79 middlewares administrador

---

controllers/membersController.js
routes/members.js

COMO usuario
QUIERO actualizar los Miembros por Id

actualizar miembros ok

---

routes/backoffice.js
routes/comments.js
routes/contacts.js
routes/members.js
routes/organization.js
routes/users.js

Standard name for the middleware

Fix Typo - RoleValidator middleware

---

controllers/newsController.js
models/comment.js
models/new.js
routes/news.js

Listar commentarios en base a una novedad

OT 85 Listar comentarios post/novedad

---

controllers/newsCategoriesController.js
routes/newsCategories.js
utils/pagination.js

COMO usuario
QUIERO visualizar los resultados de Categorías paginados

Paginacion categoria-incorporacion de responseHTTP
